services:
  - type: web
    name: the_ultimate_pug_quiz
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn pug_quiz.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false