databases:
  - name: the_ultimate_pug_quiz
    databaseName: pug_quiz
    user: cushione

services:
  - type: web
    name: the_ultimate_pug_quiz
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn pug_quiz.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pug_quiz
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4