# Generated by Django 5.0 on 2023-12-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_game_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct',
            new_name='right',
        ),
    ]
